language: node_js
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
  - npm i -g eslint
  - npm i -D eslint-plugin-react
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
